Sistemi i rekomandimit funksionon ne baze te items(produkteve) dhe ne baze te klientave p.sh nese nje klient kur e ka ble produktin A e ka ble bashke me produktin B, atehere klienteve te tjere qe blejne produktin A iu rekomandohet produkti B,funksionon ne baze te produkteve best seller,nese produktet blihen nga kliente qe jon te ngjashem ateher edhe produktet konsiderohen te ngjashme,rekomandimet do te varen nga klientet specifik dhe historia e tyre, dhe mund te ndikohen edhe nga modeli RFM-recency-frequency-monetary

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
df=pd.read_csv("../data/processed/onlineRetail_cleaned.csv")

e kena lexu dokumentin ku e kena datasetin

In [2]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 392692 entries, 0 to 392691
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    392692 non-null  int64
 1   StockCode    392692 non-null  str
 2   Description  392692 non-null  str
 3   Quantity     392692 non-null  int64
 4   InvoiceDate  392692 non-null  str
 5   UnitPrice    392692 non-null  float64
 6   CustomerID   392692 non-null  float64
 7   Country      392692 non-null  str
 8   TotalPrice   392692 non-null  float64
dtypes: float64(3), int64(2), str(4)
memory usage: 27.0 MB

In [4]:
df["CustomerID"] = df["CustomerID"].astype(int)

In [5]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

In [10]:
user_item=df.pivot_table(
    index="CustomerID",
    columns="StockCode",
    values="Quantity",
    aggfunc="sum",  
    fill_value=0
    )

In [12]:
user_item.shape

(4338, 3665)

In [13]:
user_item.head()

StockCode,10002,10080,10120,10123C,10124A,10124G,10125,10133,10135,11001,...,90214V,90214W,90214Y,90214Z,BANK CHARGES,C2,DOT,M,PADS,POST
CustomerID,,,,,,,,,,,,,,,,,,,,,
12346,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12347,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12348,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,9
12349,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
12350,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [14]:
total_values = user_item.size
zero_values = (user_item == 0).sum().sum()

sparsity = zero_values / total_values * 100

print(f"Sparsity: {sparsity:.2f}%")

Sparsity: 98.32%

98.32% e kombinimeve customer-product jane 0,tash e kena matricen ne ate forme qe na kallzon per secilin customer sa here ose sa cope produkte i ka ble,tash e bojna ne menyre veq a e ka ble a jo --purchased/not purchased ne binary ,0/not purchased  1/purchased

In [15]:
user_item_binary = (user_item > 0).astype(int)

In [16]:
user_item_binary.head()

StockCode,10002,10080,10120,10123C,10124A,10124G,10125,10133,10135,11001,...,90214V,90214W,90214Y,90214Z,BANK CHARGES,C2,DOT,M,PADS,POST
CustomerID,,,,,,,,,,,,,,,,,,,,,
12346,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12347,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12348,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
12349,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
12350,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [17]:
user_item_binary.shape

(4338, 3665)

tash fillojna me pjesen tjeter te rekomandimit qe bazohet ne collaborative filtering p.sh cilat produkte blihen nga kliente te ngjashem,me kliente te ngjashem nenkuptojme qe kan histori te blerjeve te ngjashme psh kan ble produkte te njejta etj

In [18]:
from sklearn.metrics.pairwise import cosine_similarity
item_similarity = cosine_similarity(user_item_binary.T)

.T---- per momentin kena krahasimet customer x products 4338x3665 po tash dojna me i krahasu produktet me produkte e kjo e kthen niher ne 3665 x 4338 prsa products x customers e pastaj cosine similiarity e bon 3665 x 3665

In [19]:
item_similarity.shape

(3665, 3665)

In [20]:
item_similarity[:5, :5]

array([[1.        , 0.        , 0.09486833, 0.09128709, 0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.09486833, 0.        , 1.        , 0.11547005, 0.        ],
       [0.09128709, 0.        , 0.11547005, 1.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 1.        ]])

tabela funksionon ne ate menyre psh product1Xproduct1 e ka similiarity 1 product1Xproduct2 e ka similiarity 0 ,diagonalja osht gjithmone 1 se cdo produkt osht i ngjashem me vetveten e per qat arsye duhet me i perjashtu se nuk munem me ja rekomandu personit qe e ka ble produktin A apet produktin A.Tash emrat e produkteve kan hup se cosine similiarity na ka jep veq permes numrave e tash stockCoden e lidhum me similiarity psh produkti 5430 osht similiar me produktin 2345

In [21]:
product_codes=user_item_binary.columns
product_codes[:10]

Index(['10002', '10080', '10120', '10123C', '10124A', '10124G', '10125',
       '10133', '10135', '11001'],
      dtype='str', name='StockCode')

In [22]:
product_codes[0]

'10002'

In [23]:
product_codes[1]

'10080'

In [24]:
item_similarity_df=pd.DataFrame(item_similarity, index=product_codes, columns=product_codes)

In [25]:
item_similarity_df.head()

StockCode,10002,10080,10120,10123C,10124A,10124G,10125,10133,10135,11001,...,90214V,90214W,90214Y,90214Z,BANK CHARGES,C2,DOT,M,PADS,POST
StockCode,,,,,,,,,,,,,,,,,,,,,
10002,1.000000,0.0,0.094868,0.091287,0.0,0.000000,0.090351,0.062932,0.098907,0.095346,...,0.0,0.0,0.0,0.0,0.0,0.029361,0.0,0.067591,0.0,0.078217
10080,0.000000,1.0,0.000000,0.000000,0.0,0.000000,0.032774,0.045655,0.047836,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.016345,0.0,0.000000
10120,0.094868,0.0,1.000000,0.115470,0.0,0.000000,0.057143,0.059702,0.041703,0.060302,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.071247,0.0,0.010993
10123C,0.091287,0.0,0.115470,1.000000,0.0,0.000000,0.164957,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000
10124A,0.000000,0.0,0.000000,0.000000,1.0,0.447214,0.063888,0.044499,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000

In [27]:
item_similarity_df["10002"]

StockCode
10002     1.000000
10080     0.000000
10120     0.094868
10123C    0.091287
10124A    0.000000
            ...
C2        0.029361
DOT       0.000000
M         0.067591
PADS      0.000000
POST      0.078217
Name: 10002, Length: 3665, dtype: float64

In [35]:
product_code=product_codes[1]
print(f"Product code: {product_code}")
similar_products=item_similarity_df[product_code]
similar_products = similar_products.sort_values(ascending=False)
similar_products.head(10)

Product code: 10080

StockCode
10080     1.000000
23694     0.191346
22039     0.187317
47504H    0.166924
21650     0.165567
90214F    0.162221
90206A    0.162221
79157B    0.162221
84012     0.155857
22043     0.145095
Name: 10080, dtype: float64

qitu e kena krahasu produktin e pare me kod 10080 me productet tjera edhe n anen e djath kan dal sa eshte i ngjashem edhe produktin me vetveten e hekum krahasim se gjith del 1

In [38]:
similar_products = similar_products.drop(product_code)

In [39]:
similar_products.head(10)

StockCode
23694     0.191346
22039     0.187317
47504H    0.166924
21650     0.165567
90214F    0.162221
90206A    0.162221
79157B    0.162221
84012     0.155857
22043     0.145095
21373     0.143315
Name: 10080, dtype: float64

10 produktet ma t ngjashme me produktin 10080

In [40]:
product_info=df[["StockCode", "Description"]].drop_duplicates()
product_info.head()

  StockCode                          Description
0    85123A   WHITE HANGING HEART T-LIGHT HOLDER
1     71053                  WHITE METAL LANTERN
2    84406B       CREAM CUPID HEARTS COAT HANGER
3    84029G  KNITTED UNION FLAG HOT WATER BOTTLE
4    84029E       RED WOOLLY HOTTIE WHITE HEART.

In [42]:
recommendations=similar_products.head(10).reset_index()
recommendations.columns=["StockCode", "Similarity"]

In [43]:
recommendations

  StockCode  Similarity
0     23694    0.191346
1     22039    0.187317
2    47504H    0.166924
3     21650    0.165567
4    90214F    0.162221
5    90206A    0.162221
6    79157B    0.162221
7     84012    0.155857
8     22043    0.145095
9     21373    0.143315

In [44]:
recommendations=recommendations.merge(
    product_info, 
    on="StockCode",
    how="left"
)

In [45]:
recommendations

  StockCode  Similarity                          Description
0     23694    0.191346                    PAISLEY PARK CARD
1     22039    0.187317             BOTANICAL LILY GIFT WRAP
2    47504H    0.166924           ENGLISH ROSE SPIRIT LEVEL
3     21650    0.165567       ASSORTED TUTTI FRUTTI BRACELET
4    90214F    0.162221            LETTER "F" BLING KEY RING
5    90206A    0.162221            GOLD DIAMANTE STAR BROOCH
6    79157B    0.162221              UBO-LIGHT TRIOBASE BLUE
7     84012    0.155857  MAGIC SHEEP WOOL GROWING FROM PAPER
8     22043    0.145095         CHRISTMAS CARD SCREEN PRINT
9     21373    0.143315         MIRRORED WALL ART SNOWFLAKES

In [46]:
def recommend_products(product_code, n=5):
    if product_code not in item_similarity_df.index:
        return pd.DataFrame(columns=["StockCode", "Similarity", "Description"])
    similarities=item_similarity_df[product_code]
    similarities = similarities.drop(product_code)
    top_products = similarities.sort_values(
    ascending=False
    ).head(n)
    recommendations = top_products.reset_index()
    recommendations.columns = ["StockCode", "Similarity"]
    recommendations = recommendations.merge(
        product_info,
        on="StockCode",
        how="left"
    )
    return recommendations

In [47]:
recommend_products("10002", n=5)

  StockCode  Similarity                        Description
0     90103    0.223607         PURPLE FRANGIPANI NECKLACE
1     21826    0.197642           EIGHT PIECE DINOSAUR SET
2    90059E    0.182574     DIAMANTE HAIR GRIP PACK/2 RUBY
3     90101    0.182574          WHITE FRANGIPANI NECKLACE
4    90059F    0.182574  DIAMANTE HAIR GRIP PACK/2 LT ROSE

In [49]:
recommend_products("ABDER", n=10)

Empty DataFrame
Columns: [StockCode, Similarity, Description]
Index: []

e kena kriju funksionin recommend_products i cili kur e jepum psh produktin 10002 e kqyr mas pari a ekziston qiky produkt , nese s ekziston e kthen veq stock code,similarity edhe description si dataframe po bosh.Pastaj i gjen produktet e ngjashme me qat produkt permes product_code,edhe e hek vetveten e bon drop i merr top produktet pra vlerat e tyne edhe i rendit ne rend prej ma t madhit deri tek ma i vogli edhe permes head(n) varesisht sa e ka vleren n qato i shfaq,tash qitynev top products i shfaq me index te stock code dmth jav hek indexin e vetkrijum edhe i shfaq permes kolonave stock code dhe similarity

In [50]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [51]:
df["InvoiceDate"].min(), df["InvoiceDate"].max()

(Timestamp('2010-12-01 08:26:00'), Timestamp('2011-12-09 12:50:00'))

In [52]:
cutoff_date = df["InvoiceDate"].quantile(0.8)

train_df = df[df["InvoiceDate"] <= cutoff_date].copy()

test_df = df[df["InvoiceDate"] > cutoff_date].copy()

In [53]:
print("Cutoff:", cutoff_date)
print("Train:", train_df.shape)
print("Test:", test_df.shape)

Cutoff: 2011-11-01 15:55:00
Train: (314183, 9)
Test: (78509, 9)

tash kena fillu testimin e recommandation system ne pjesen train edhe test,train per me pa se qfare produktesh kan ble klientat baze te tynev modeli u rekomandon produktet tjera,kurse test oer me pa se a i kan ble klientat produktet e rekomandume

In [56]:
train_user_item=train_df.pivot_table(
    index="CustomerID",
    columns="StockCode",
    values="Quantity",
    aggfunc="sum",
    fill_value=0
)

e kena kriju ni user matrix po nkit rast me t dhanat e train_df tek train_df jo tek df i pergjithshem pra veq deri me daten ku e kena nda 2011-11-01

In [57]:
train_user_item_binary = (train_user_item > 0).astype(int)

In [58]:
print(train_user_item.shape)

(3985, 3614)

In [59]:
print(train_user_item_binary.shape)

(3985, 3614)

In [60]:
from sklearn.metrics.pairwise import cosine_similarity
train_item_similarity = cosine_similarity(train_user_item_binary.T)
print(train_item_similarity.shape)

(3614, 3614)

secilin produkt e krahasojme me produktin tjeter per me gjet similarity qata na ka dal 3614,3614

In [61]:
train_item_similarity_df=pd.DataFrame(train_item_similarity,
     index=train_user_item_binary.columns, 
     columns=train_user_item_binary.columns)
train_item_similarity_df.head()

StockCode,10002,10080,10120,10123C,10124A,10124G,10125,10133,10135,11001,...,90214R,90214S,90214V,90214Y,BANK CHARGES,C2,DOT,M,PADS,POST
StockCode,,,,,,,,,,,,,,,,,,,,,
10002,1.000000,0.0,0.106066,0.091287,0.0,0.000000,0.092253,0.062932,0.087304,0.103975,...,0.0,0.0,0.0,0.0,0.0,0.030429,0.0,0.073193,0.0,0.064008
10080,0.000000,1.0,0.000000,0.000000,0.0,0.000000,0.037662,0.051383,0.057027,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000
10120,0.106066,0.0,1.000000,0.129099,0.0,0.000000,0.065233,0.066749,0.024693,0.073521,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.069007,0.0,0.012932
10123C,0.091287,0.0,0.129099,1.000000,0.0,0.000000,0.168430,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000
10124A,0.000000,0.0,0.000000,0.000000,1.0,0.288675,0.072932,0.049752,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000

In [62]:
train_item_similarity_df["10080"]

StockCode
10002     0.0
10080     1.0
10120     0.0
10123C    0.0
10124A    0.0
         ...
C2        0.0
DOT       0.0
M         0.0
PADS      0.0
POST      0.0
Name: 10080, Length: 3614, dtype: float64

In [63]:
similar_products = train_item_similarity_df["10080"].drop("10080")

similar_products = similar_products.sort_values(
    ascending=False
)

similar_products.head(10)

StockCode
79157B    0.258199
22039     0.210819
84012     0.196875
47504H    0.184428
79157V    0.182574
90206A    0.182574
47503H    0.161515
22043     0.151911
84984D    0.149071
72709     0.149071
Name: 10080, dtype: float64

deri qitu e kena pa qe modeli ne pjesen train po funksionon pra pi rekomandon produktet e ngjashme e te pjesa test po dojna me pa a po funksionon mire parashikimi p.sh per produktin me stock code 10080 produkti ma similar osht produkti 79157B,tash mbetet mu pa ne pjesen test se klienti nese e ka ble produktin  10080 a e ka ble edhe 79157B

In [64]:
train_customers = set(train_df["CustomerID"].unique())
test_customers = set(test_df["CustomerID"].unique())

common_customers = train_customers.intersection(test_customers)

len(common_customers)

1530

i kena 1530 customers te perbashket edhe ne pjesen train edhe ne pjesen test

In [65]:
customer_id = list(common_customers)[0]

customer_id

np.int64(16386)

In [68]:
customer_train=train_df[
    train_df["CustomerID"] == customer_id
]
customer_train[["CustomerID", "StockCode", "Description", "Quantity"]].head(10)

       CustomerID StockCode                         Description  Quantity
92615       16386     22264       FELT FARM ANIMAL WHITE BUNNY         12
92616       16386    84997A   CHILDRENS CUTLERY POLKADOT GREEN          4
92617       16386    84997D     CHILDRENS CUTLERY POLKADOT PINK         4
92618       16386     22328  ROUND SNACK BOXES SET OF 4 FRUITS          6

qitu kena tregu qka ka ble qiky customer para qasaj date qe e kena nda te pjesa train dmth cut off

In [70]:
customer_test=test_df[
    test_df["CustomerID"] == customer_id

]

customer_test[["CustomerID", "StockCode", "Description", "Quantity"]].head(5)

        CustomerID StockCode                       Description  Quantity
334020       16386    85032A     ROMANTIC IMAGES GIFT WRAP SET         1
334021       16386     22558   CLOTHES PEGS RETROSPOT PACK 24          2
334022       16386     23254     CHILDRENS CUTLERY DOLLY GIRL          1
334023       16386     84946      ANTIQUE SILVER T-LIGHT GLASS         6
334024       16386     21326  AGED GLASS SILVER T-LIGHT HOLDER        12

In [71]:
def get_customer_products(customer_id):
    products=train_user_item_binary.loc[customer_id]    
    products=products[products>0].index.tolist()
    return products

In [72]:
customer_id=list(common_customers)[0]
customer_products=get_customer_products(customer_id)
customer_products

['22264', '22328', '84997A', '84997D']

In [74]:
recommendations={}

for product in customer_products:
   similar=train_item_similarity_df[product].drop(product)  
   similar=similar.sort_values(ascending=False)
   recommendations[product] = similar.head(5)

In [75]:
def get_customer_products(customer_id):
    products = train_user_item_binary.loc[customer_id]
    products = products[products > 0].index.tolist()
    return products

In [76]:
customer_id = list(common_customers)[0]

customer_products = get_customer_products(customer_id)

customer_products

['22264', '22328', '84997A', '84997D']

In [77]:
recommendations={}

for product in customer_products:
   similar=train_item_similarity_df[product].drop(product)  
   similar=similar.sort_values(ascending=False)
   recommendations[product] = similar.head(5)

In [78]:
recommendations

{'22264': StockCode
 22255     0.324443
 22254     0.245256
 22259     0.243332
 90180B    0.229416
 22258     0.225913
 Name: 22264, dtype: float64,
 '22328': StockCode
 22326    0.594527
 21559    0.384993
 22327    0.379461
 22631    0.370483
 22629    0.347663
 Name: 22328, dtype: float64,
 '84997A': StockCode
 84997B    0.689062
 84997D    0.599536
 84997C    0.592342
 21238     0.279783
 20674     0.275330
 Name: 84997A, dtype: float64,
 '84997D': StockCode
 84997C    0.769117
 84997B    0.648249
 84997A    0.599536
 23256     0.401459
 21239     0.366381
 Name: 84997D, dtype: float64}

In [79]:
candidate_scores = []

for product, similar_products in recommendations.items():
    for recommended_product, similarity in similar_products.items():
        candidate_scores.append({
            "StockCode": recommended_product,
            "Similarity": similarity,
            "SourceProduct": product
        })

In [80]:
candidates_df = pd.DataFrame(candidate_scores)

candidates_df

   StockCode  Similarity SourceProduct
0      22255    0.324443         22264
1      22254    0.245256         22264
2      22259    0.243332         22264
3     90180B    0.229416         22264
4      22258    0.225913         22264
5      22326    0.594527         22328
6      21559    0.384993         22328
7      22327    0.379461         22328
8      22631    0.370483         22328
9      22629    0.347663         22328
10    84997B    0.689062        84997A
11    84997D    0.599536        84997A
12    84997C    0.592342        84997A
13     21238    0.279783        84997A
14     20674    0.275330        84997A
15    84997C    0.769117        84997D
16    84997B    0.648249        84997D
17    84997A    0.599536        84997D
18     23256    0.401459        84997D
19     21239    0.366381        84997D

In [81]:
candidates_df = candidates_df[
    ~candidates_df["StockCode"].isin(customer_products)
]

In [82]:
candidates_df

   StockCode  Similarity SourceProduct
0      22255    0.324443         22264
1      22254    0.245256         22264
2      22259    0.243332         22264
3     90180B    0.229416         22264
4      22258    0.225913         22264
5      22326    0.594527         22328
6      21559    0.384993         22328
7      22327    0.379461         22328
8      22631    0.370483         22328
9      22629    0.347663         22328
10    84997B    0.689062        84997A
12    84997C    0.592342        84997A
13     21238    0.279783        84997A
14     20674    0.275330        84997A
15    84997C    0.769117        84997D
16    84997B    0.648249        84997D
18     23256    0.401459        84997D
19     21239    0.366381        84997D

In [83]:
candidates_df = candidates_df.reset_index(drop=True)

In [84]:
final_recommendations = (
    candidates_df
    .groupby("StockCode")["Similarity"]
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)

In [85]:
final_recommendations

   StockCode  Similarity
0     84997C    0.680729
1     84997B    0.668656
2      22326    0.594527
3      23256    0.401459
4      21559    0.384993
5      22327    0.379461
6      22631    0.370483
7      21239    0.366381
8      22629    0.347663
9      22255    0.324443
10     21238    0.279783
11     20674    0.275330
12     22254    0.245256
13     22259    0.243332
14    90180B    0.229416
15     22258    0.225913

i kena rendit produktet e rekomanduara sipas mesatareve tyre se psh do produkte jon rekomandu disa here e disa tjera jo

In [86]:
customer_products=get_customer_products(customer_id)
bought_products=set(customer_products)
bought_products

{'22264', '22328', '84997A', '84997D'}

In [ ]:
recommendations=all_recommendations[
    ~all_recommendations["StockCode"].isin(bought_products)
]

i marrum krejt produktet stock code qe nuk jon te produktet e bleme prej klientit qe me perjashtu rekomandimin e produkteve te blera

In [94]:
type(recommendations)

dict

In [95]:
recommendations_list = []

for source_product, recs in recommendations.items():
    temp = recs.reset_index()
    temp.columns = ["StockCode", "Similarity"]
    temp["SourceProduct"] = source_product
    recommendations_list.append(temp)

all_recommendations_df = pd.concat(
    recommendations_list,
    ignore_index=True
)

In [96]:
all_recommendations_df

   StockCode  Similarity SourceProduct
0      22255    0.324443         22264
1      22254    0.245256         22264
2      22259    0.243332         22264
3     90180B    0.229416         22264
4      22258    0.225913         22264
5      22326    0.594527         22328
6      21559    0.384993         22328
7      22327    0.379461         22328
8      22631    0.370483         22328
9      22629    0.347663         22328
10    84997B    0.689062        84997A
11    84997D    0.599536        84997A
12    84997C    0.592342        84997A
13     21238    0.279783        84997A
14     20674    0.275330        84997A
15    84997C    0.769117        84997D
16    84997B    0.648249        84997D
17    84997A    0.599536        84997D
18     23256    0.401459        84997D
19     21239    0.366381        84997D

In [103]:
bought_products = set(customer_products)

filtered_recommendations = all_recommendations_df[
    ~all_recommendations_df["StockCode"].isin(bought_products)

]

In [106]:
filtered_recommendations = filtered_recommendations.sort_values(
  
    "Similarity",
    ascending=False
  
    
)

In [109]:
top_5 = filtered_recommendations.head(5)

top_5Unique=top_5.drop_duplicates("StockCode")
top_5Unique

   StockCode  Similarity SourceProduct
15    84997C    0.769117        84997D
10    84997B    0.689062        84997A
5      22326    0.594527         22328

In [110]:
customer_id = list(common_customers)[0]
test_products=test_df[
    test_df["CustomerID"] == customer_id

]["StockCode"].unique().tolist()

test_products

['85032A',
 '22558',
 '23254',
 '84946',
 '21326',
 '84945',
 '23378',
 '23377',
 '23379',
 '21981',
 '20679',
 '22094',
 '22091',
 '22096',
 '21034',
 '23344',
 '21928',
 '22385',
 '23582',
 '35471D',
 '23367',
 '20973',
 '20974',
 '23307',
 '22993',
 '22087',
 '23080',
 '22098',
 '84926F',
 '47578A',
 '20832',
 '21947',
 '22195',
 '23281',
 '23282',
 '84347',
 '84952A',
 '84596B',
 '22941',
 '84997A',
 '22578',
 '72817',
 '16219',
 '21990',
 '84978',
 '21556',
 '22197',
 '21918',
 '90114',
 '85099B',
 '23203',
 '21579',
 '23306',
 '21894',
 '84992',
 '84879',
 '23290',
 '23289',
 '22423',
 '23354',
 '21058',
 '23570',
 '23229',
 '47310M',
 '21980',
 '21982',
 '22535',
 '22995',
 '23499',
 '23497',
 '21190',
 '85032B',
 '85032C']

i kena marr produktet te pjesa e testit me kqyr ku ja kena qellu prediction

In [111]:
recommended_products = top_5Unique["StockCode"].tolist()
recommended_products

['84997C', '84997B', '22326']

In [112]:
hits=set(recommended_products) & set(test_products)
hits

set()

In [113]:
len(hits)

0

kjo dmth qe per ni customer qe e kena marr si shembull moideli se ka qellu po kjo sdmth qe modeli osht gabim na e testojna tash per krejt customers jo veq per njo

In [114]:
len(common_customers)

1530

In [116]:
evaluation_results = []
for customer_id in common_customers:
    print(customer_id)

16386
16393
16399
16401
16407
16409
16411
16414
16416
16422
16426
16434
16438
16440
16442
16446
16458
16460
16463
16464
16466
16469
16474
16478
16488
16495
16496
16500
16506
16511
16513
16519
16523
16525
16531
16532
16533
16539
16549
16555
16557
16558
16560
16561
16566
16570
16571
16592
16596
16600
16607
16609
16612
16616
16618
16620
16626
16628
16633
16637
16638
16639
16642
16653
16655
16656
16657
16660
16668
16669
16670
16671
16672
16676
16678
16682
16684
16688
16700
16701
16705
16706
16710
16711
16712
16713
16717
16719
16722
16726
16743
16744
16746
16747
16748
16762
16764
16767
16771
16775
16779
16782
16791
16794
16804
16809
16813
16814
16817
16818
16824
16833
16837
16839
16841
16851
16852
16855
16863
16869
16871
16873
16877
16880
16885
16891
16892
16898
16899
16900
16904
16905
16907
16910
16912
16915
16916
16923
16924
16929
16930
16931
16933
16938
16942
16945
16949
16954
16966
16968
16979
16983
16985
16987
16989
16992
16996
16999
17001
17006
17014
17015
17017
17019
17031
17034
17041
17042
17043
17049
17054
17059
17063
17068
17069
17071
17073
17075
17076
17080
17081
17082
17086
17088
17090
17091
17095
17096
17097
17101
17107
17109
17114
17115
17119
17131
17133
17135
17139
17144
17147
17155
17157
17158
17159
17160
17162
17163
17164
17173
17183
17188
17191
17193
17198
17203
17211
17218
17220
17227
17228
17231
17235
17236
17238
17243
17250
17266
17287
17288
17289
17293
17295
17299
17302
17306
17314
17315
17321
17323
17324
17329
17330
17338
17340
17345
17346
17348
17350
17351
17360
17364
17365
17368
17371
17377
17381
17384
17386
17389
17402
17404
17405
17410
17411
17412
17416
17419
17422
17425
17426
17428
17430
17434
17436
17442
17449
17450
17451
17453
17463
17466
17469
17481
17490
17491
17495
17503
17511
17512
17515
17516
17519
17521
17522
17526
17528
17530
17537
17540
17549
17554
17555
17557
17562
17564
17567
17573
17576
17579
17581
17584
17590
17593
17596
17602
17611
17613
17618
17621
17624
17625
17629
17631
17633
17634
17637
17644
17651
17652
17653
17655
17658
17659
17663
17664
17666
17668
17671
17673
17675
17676
17677
17682
17685
17686
17690
17700
17702
17703
17705
17706
17711
17716
17719
17720
17725
17728
17730
17735
17736
17737
17738
17739
17744
17750
17754
17757
17758
17759
17760
17768
17769
17777
17779
17790
17797
17799
17800
17809
17811
17812
17813
17816
17817
17827
17828
17830
17838
17841
17856
17857
17858
17861
17864
17865
17867
17870
17883
17884
17886
17888
17920
17924
17929
17930
17932
17937
17949
17954
17961
17964
17965
17966
17974
17975
17979
17988
17999
18001
18005
18016
18030
18035
18036
18040
18041
18043
18044
18055
18059
18061
18065
18069
18075
18077
18080
18081
18092
18096
18097
18101
18102
18109
18112
18118
18122
18125
18127
18130
18135
18144
18145
18150
18154
18156
18158
18161
18167
18170
18172
18177
18179
18180
18188
18198
18205
18210
18211
18217
18219
18221
18223
18225
18229
18230
18236
18237
18241
18245
18246
18259
18263
18272
18273
18282
18283
12347
12352
12356
12358
12362
12364
12375
12380
12381
12384
12388
12395
12397
12406
12408
12415
12417
12421
12423
12427
12428
12429
12431
12433
12437
12438
12444
12449
12451
12462
12464
12465
12471
12472
12473
12474
12476
12477
12480
12481
12483
12484
12488
12490
12494
12498
12500
12517
12518
12523
12524
12526
12528
12539
12540
12541
12553
12557
12560
12562
12567
12569
12572
12576
12577
12578
12583
12584
12589
12594
12597
12598
12599
12600
12610
12615
12619
12620
12621
12626
12627
12628
12630
12640
12642
12645
12646
12647
12654
12656
12657
12662
12664
12668
12670
12673
12676
12680
12681
12682
12683
12684
12685
12689
12691
12695
12697
12700
12704
12705
12708
12709
12712
12714
12716
12719
12720
12721
12723
12724
12726
12727
12731
12747
12748
12749
12753
12757
12766
12775
12778
12779
12782
12783
12787
12798
12808
12820
12826
12827
12828
12830
12832
12838
12839
12841
12844
12849
12856
12865
12867
12877
12883
12901
12904
12906
12910
12912
12913
12919
12921
12925
12928
12931
12933
12935
12936
12937
12944
12948
12949
12951
12952
12955
12957
12962
12963
12970
12971
12981
12989
12990
12991
12993
12994
12997
13001
13004
13012
13013
13014
13018
13021
13026
13028
13029
13030
13046
13047
13048
13050
13058
13064
13068
13069
13077
13078
13079
13081
13083
13089
13090
13094
13097
13098
13102
13104
13110
13113
13115
13117
13118
13126
13131
13137
13138
13139
13147
13148
13149
13155
13159
13167
13168
13171
13173
13174
13178
13183
13184
13189
13196
13198
13199
13200
13203
13207
13209
13211
13212
13225
13230
13232
13236
13238
13246
13247
13255
13258
13263
13266
13267
13268
13269
13272
13277
13282
13285
13297
13305
13308
13309
13310
13311
13313
13314
13316
13319
13323
13324
13329
13350
13362
13363
13365
13379
13381
13384
13389
13394
13396
13404
13408
13410
13417
13418
13426
13427
13429
13430
13435
13437
13448
13450
13451
13455
13456
13458
13460
13468
13471
13477
13488
13495
13496
13499
13500
13502
13507
13509
13510
13516
13523
13525
13527
13534
13536
13546
13549
13557
13558
13565
13569
13571
13575
13576
13577
13579
13588
13589
13590
13592
13599
13606
13610
13614
13623
13629
13630
13632
13634
13636
13643
13644
13647
13650
13651
13657
13658
13668
13680
13681
13685
13692
13694
13695
13700
13704
13705
13709
13717
13719
13728
13735
13736
13742
13743
13755
13756
13758
13759
13767
13769
13772
13777
13780
13782
13784
13798
13804
13808
13810
13815
13816
13817
13822
13823
13824
13831
13835
13838
13846
13854
13860
13862
13867
13868
13870
13871
13880
13881
13882
13883
13884
13890
13892
13894
13895
13899
13904
13924
13928
13939
13940
13941
13949
13950
13953
13954
13956
13960
13962
13969
13971
13975
13978
13983
13984
13985
13988
13991
13994
13995
13999
14005
14020
14023
14030
14031
14032
14034
14035
14044
14047
14049
14050
14051
14056
14057
14060
14062
14064
14071
14075
14083
14085
14088
14092
14096
14099
14102
14108
14110
14111
14112
14113
14116
14121
14125
14129
14132
14135
14138
14141
14146
14150
14156
14157
14159
14173
14178
14180
14188
14189
14191
14194
14198
14205
14209
14214
14215
14217
14226
14227
14234
14240
14243
14250
14251
14258
14262
14277
14282
14284
14285
14286
14287
14289
14290
14291
14292
14293
14297
14298
14299
14309
14321
14329
14332
14334
14335
14336
14342
14359
14360
14367
14387
14388
14390
14395
14397
14401
14404
14408
14415
14416
14418
14419
14422
14426
14428
14432
14434
14440
14441
14446
14447
14448
14449
14452
14456
14466
14467
14470
14477
14482
14487
14493
14499
14502
14503
14505
14506
14507
14508
14511
14515
14517
14520
14522
14524
14525
14527
14530
14533
14534
14539
14540
14543
14544
14546
14547
14550
14551
14553
14554
14560
14562
14572
14577
14583
14587
14591
14592
14593
14594
14595
14597
14606
14607
14608
14618
14621
14623
14626
14629
14636
14640
14646
14649
14653
14655
14657
14658
14659
14662
14667
14673
14676
14680
14684
14688
14691
14696
14698
14700
14701
14702
14704
14708
14709
14710
14711
14712
14713
14715
14719
14720
14723
14730
14732
14733
14735
14737
14739
14741
14744
14748
14755
14759
14765
14766
14768
14769
14784
14790
14794
14796
14805
14815
14820
14824
14825
14829
14834
14849
14851
14853
14856
14859
14862
14865
14866
14868
14869
14871
14878
14883
14895
14897
14898
14901
14903
14907
14910
14911
14912
14913
14921
14931
14936
14944
14948
14960
14961
14963
14971
14984
14987
15005
15021
15022
15023
15024
15027
15028
15031
15033
15034
15039
15044
15046
15050
15051
15053
15054
15058
15061
15065
15073
15078
15081
15088
15089
15093
15101
15103
15105
15106
15110
15111
15113
15114
15116
15117
15123
15124
15125
15132
15134
15136
15144
15145
15150
15152
15157
15159
15163
15172
15179
15184
15186
15187
15189
15194
15197
15203
15206
15208
15214
15218
15227
15237
15238
15239
15249
15251
15252
15253
15267
15270
15271
15287
15289
15290
15291
15297
15298
15311
15330
15344
15351
15355
15356
15358
15365
15373
15380
15382
15392
15393
15394
15398
15399
15406
15407
15411
15414
15426
15427
15429
15434
15436
15443
15444
15449
15452
15453
15465
15467
15473
15482
15484
15485
15489
15492
15493
15494
15497
15498
15500
15502
15506
15511
15513
15514
15522
15525
15527
15529
15530
15532
15533
15544
15547
15550
15555
15561
15563
15568
15570
15571
15572
15573
15582
15584
15594
15599
15601
15602
15605
15608
15611
15612
15615
15618
15628
15632
15640
15651
15660
15671
15676
15679
15680
15681
15687
15690
15694
15696
15701
15707
15712
15714
15719
15722
15727
15737
15738
15743
15745
15747
15750
15755
15763
15769
15781
15782
15785
15787
15793
15796
15804
15805
15809
15811
15814
15822
15838
15839
15845
15850
15854
15856
15858
15861
15862
15863
15864
15867
15898
15901
15903
15906
15907
15910
15916
15919
15932
15933
15948
15949
15950
15951
15952
15953
15955
15963
15965
15967
15969
15971
15977
15981
15983
15984
15987
15993
15998
16003
16005
16008
16009
16011
16012
16013
16014
16015
16016
16020
16033
16038
16041
16042
16043
16053
16057
16062
16066
16076
16079
16085
16094
16103
16107
16115
16119
16126
16128
16133
16134
16139
16143
16145
16149
16156
16157
16161
16164
16168
16169
16173
16185
16186
16187
16189
16191
16200
16201
16205
16210
16212
16218
16221
16240
16241
16242
16243
16245
16255
16261
16265
16271
16279
16283
16284
16293
16295
16298
16303
16308
16311
16313
16326
16327
16330
16332
16333
16341
16348
16350
16353
16357
16358
16359
16360
16361
16362
16364
16365
16367
16369
16379

In [121]:
evaluation_results = []

for customer_id in common_customers:

    customer_products = get_customer_products(customer_id)

    customer_recommendations = {}

    for product in customer_products:

        if product in train_item_similarity_df.index:

            similar_products = (
                train_item_similarity_df[product]
                .drop(product)
                .sort_values(ascending=False)
                .head(5)
            )

            customer_recommendations[product] = similar_products

    recommendations_list = []

    for source_product, recs in customer_recommendations.items():

        temp = recs.reset_index()

        temp.columns = ["StockCode", "Similarity"]

        temp["SourceProduct"] = source_product

        recommendations_list.append(temp)

    if not recommendations_list:
        continue

    all_recommendations_df = pd.concat(
        recommendations_list,
        ignore_index=True
    )

    bought_products = set(customer_products)

    filtered_recommendations = all_recommendations_df[
        ~all_recommendations_df["StockCode"].isin(bought_products)
    ]

    recommendations_unique = (
        filtered_recommendations
        .sort_values("Similarity", ascending=False)
        .drop_duplicates("StockCode")
    )

    top_5Unique = recommendations_unique.head(5)

    test_products = test_df[
        test_df["CustomerID"] == customer_id
    ]["StockCode"].unique().tolist()

    recommended_products = top_5Unique["StockCode"].tolist()

    hits = set(recommended_products) & set(test_products)

    evaluation_results.append({
        "CustomerID": customer_id,
        "Recommended": recommended_products,
        "TestProducts": test_products,
        "Hits": list(hits),
        "HitCount": len(hits)
    })

In [122]:
evaluation_df = pd.DataFrame(evaluation_results)

evaluation_df.head()

,CustomerID,Recommended,TestProducts,Hits,HitCount
0,16386,"[84997C, 84997B, 22326, 23256, 21559]","[85032A, 22558, 23254, 84946, 21326, 84945, 23...",[],0
1,16393,"[22748, 23287, 22747, 23288, 23301]","[22629, 22659, 23598, 21156, 22899, 22898, 223...",[],0
2,16399,"[22676, 22679, 22677, 22682, 22683]","[21326, 85071A, 85071B, 85071D, 85071C, 22835,...",[],0
3,16401,"[23199, 21244, 20674, 21928, 21240]","[22197, 23583, 21592, 22554, 22557, 22556, 225...","[21928, 20674]",2
4,16407,"[22685, 22805, 82551, 22775, 23395]","[23330, 84879, 22694, 22187, 21733, 22804, 824...",[],0

In [123]:
total_customers = len(evaluation_df)

customers_with_hits = (
    evaluation_df["HitCount"] > 0
).sum()

hit_rate = customers_with_hits / total_customers

print("Total customers evaluated:", total_customers)
print("Customers with at least one hit:", customers_with_hits)
print("Hit Rate:", hit_rate)

Total customers evaluated: 1530
Customers with at least one hit: 291
Hit Rate: 0.19019607843137254

In [124]:
precision_at_5 = (
    evaluation_df["HitCount"] / 5
).mean()

print("Precision@5:", precision_at_5)

Precision@5: 0.048235294117647064

In [125]:
evaluation_df["RecallAt5"] = (
    evaluation_df["HitCount"] /
    evaluation_df["TestProducts"].apply(len)
)

recall_at_5 = evaluation_df["RecallAt5"].mean()

print("Recall@5:", recall_at_5)

Recall@5: 0.010315485855422725

In [126]:
evaluation_df.head()

,CustomerID,Recommended,TestProducts,Hits,HitCount,RecallAt5
0,16386,"[84997C, 84997B, 22326, 23256, 21559]","[85032A, 22558, 23254, 84946, 21326, 84945, 23...",[],0,0.000000
1,16393,"[22748, 23287, 22747, 23288, 23301]","[22629, 22659, 23598, 21156, 22899, 22898, 223...",[],0,0.000000
2,16399,"[22676, 22679, 22677, 22682, 22683]","[21326, 85071A, 85071B, 85071D, 85071C, 22835,...",[],0,0.000000
3,16401,"[23199, 21244, 20674, 21928, 21240]","[22197, 23583, 21592, 22554, 22557, 22556, 225...","[21928, 20674]",2,0.052632
4,16407,"[22685, 22805, 82551, 22775, 23395]","[23330, 84879, 22694, 22187, 21733, 22804, 824...",[],0,0.000000

In [127]:
evaluation_df["Hit"] = evaluation_df["HitCount"] > 0

In [128]:
evaluation_df[[
    "CustomerID",
    "Recommended",
    "TestProducts",
    "Hits",
    "HitCount",
    "Hit"
]].head(10)

,CustomerID,Recommended,TestProducts,Hits,HitCount,Hit
0,16386,"[84997C, 84997B, 22326, 23256, 21559]","[85032A, 22558, 23254, 84946, 21326, 84945, 23...",[],0,False
1,16393,"[22748, 23287, 22747, 23288, 23301]","[22629, 22659, 23598, 21156, 22899, 22898, 223...",[],0,False
2,16399,"[22676, 22679, 22677, 22682, 22683]","[21326, 85071A, 85071B, 85071D, 85071C, 22835,...",[],0,False
3,16401,"[23199, 21244, 20674, 21928, 21240]","[22197, 23583, 21592, 22554, 22557, 22556, 225...","[21928, 20674]",2,True
4,16407,"[22685, 22805, 82551, 22775, 23395]","[23330, 84879, 22694, 22187, 21733, 22804, 824...",[],0,False
5,16409,"[21668, 21671, 21672, 82486, 21755]","[22603, 22573, 22578, 22571, 22572, 22579, 233...",[21755],1,True
6,16411,"[22698, 22699, 21914, 21755, 22233]","[23198, 22110, 23439, 22865, 22867, 23294, 235...",[],0,False
7,16414,"[20749, 21216, 84947, 21843, 21218]","[20750, 21217, 23491, 23067]",[],0,False
8,16416,"[23293, 82486, 21928, 23451, 23322]","[21340, 23462, 22795, 82494L, 82482, 23152, 23...",[82486],1,True
9,16422,"[21124, 72351A, 20675, 21240, 20961]","[22759, 21821, 21086, 20974, 47599B, 21380, 22...",[],0,False

In [129]:
print(type(recommendations_unique))

<class 'pandas.DataFrame'>

In [130]:
type(evaluation_results)

list

In [131]:
recommendations_data = []

for result in evaluation_results:
    customer_id = result["CustomerID"]
    recommended = result["Recommended"]

    for rank, product in enumerate(recommended, start=1):
        recommendations_data.append({
            "CustomerID": customer_id,
            "RecommendedProduct": product,
            "Rank": rank
        })

recommendations_df = pd.DataFrame(recommendations_data)

recommendations_df.to_csv(
    "../data/outputs/recommendations.csv",
    index=False
)

recommendations_df.head(10)

   CustomerID RecommendedProduct  Rank
0       16386             84997C     1
1       16386             84997B     2
2       16386              22326     3
3       16386              23256     4
4       16386              21559     5
5       16393              22748     1
6       16393              23287     2
7       16393              22747     3
8       16393              23288     4
9       16393              23301     5

In [132]:
import os

print(os.path.exists("../data/outputs/customer_segments.csv"))
print(os.path.exists("../data/outputs/recommendations.csv"))

True
True

In [133]:
import sys
sys.path.insert(0, "..")

In [134]:
from src.recommendation import (
    create_user_item_matrix,
    create_binary_matrix,
    calculate_item_similarity,
    get_product_info,
    recommend_products,
    recommend_for_customer
)

In [135]:
df = pd.read_csv(
    "../data/processed/onlineRetail_cleaned.csv"
)

df["CustomerID"] = df["CustomerID"].astype(int)

In [136]:
user_item = create_user_item_matrix(df)

print(user_item.shape)

(4338, 3665)

In [137]:
user_item_binary = create_binary_matrix(
    user_item
)

print(user_item_binary.shape)

(4338, 3665)

In [138]:
item_similarity_df = calculate_item_similarity(
    user_item_binary
)

print(item_similarity_df.shape)

(3665, 3665)

In [139]:
product_info = get_product_info(df)

product_info.head()

  StockCode                          Description
0    85123A   WHITE HANGING HEART T-LIGHT HOLDER
1     71053                  WHITE METAL LANTERN
2    84406B       CREAM CUPID HEARTS COAT HANGER
3    84029G  KNITTED UNION FLAG HOT WATER BOTTLE
4    84029E       RED WOOLLY HOTTIE WHITE HEART.

In [140]:
recommend_products(
    "10002",
    item_similarity_df,
    product_info,
    n=5
)

  StockCode  Similarity                        Description
0     90103    0.223607         PURPLE FRANGIPANI NECKLACE
1     21826    0.197642           EIGHT PIECE DINOSAUR SET
2    90059E    0.182574     DIAMANTE HAIR GRIP PACK/2 RUBY
3     90101    0.182574          WHITE FRANGIPANI NECKLACE
4    90059F    0.182574  DIAMANTE HAIR GRIP PACK/2 LT ROSE

In [141]:
customer_id = user_item_binary.index[0]

customer_id

np.int64(12346)

In [142]:
customer_recommendations = recommend_for_customer(
    customer_id,
    user_item_binary,
    item_similarity_df,
    n=5
)

customer_recommendations

  StockCode  Similarity
2     23165    0.671897
3     23167    0.659551
1     22993    0.274724
4     23307    0.262526
0     22722    0.249053

In [143]:
user_item_binary = create_binary_matrix(
    user_item
)

print(user_item_binary.shape)

(4338, 3665)

In [144]:
from src.recommendation import (
    create_user_item_matrix,
    calculate_item_similarity,
    recommend_products
)

In [145]:
user_item_binary = create_user_item_matrix(df)
print(user_item_binary.shape)

(4338, 3665)

In [ ]:
item_similarity_df = calculate_item_similarity(user_item_binary)
print(item_similarity_df.shape)

(3665, 3665)

: